function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 19-May-2020 10:21:17

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N      = 2;      % Order
    % Fstop1 = 300;    % First Stopband Frequency
    % Fstop2 = 3400;   % Second Stopband Frequency
    % Astop  = 80;     % Stopband Attenuation (dB)
    % Fs     = 44100;  % Sampling Frequency
    %
    % h = fdesign.bandpass('n,fst1,fst2,ast', N, Fstop1, Fstop2, Astop, Fs);
    %
    % Hd = design(h, 'cheby2', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.97894333413565 0.999955101197955], ...
        'ScaleValues', [2.24494010224582e-05; 1]);
end

s = double(x);
y = step(Hd,s);

